#!/usr/bin/env python3
"""Generate the library's machine indexes from the files (L-A2).

`library/prompts/index.yaml` is derived from the .txt prompt files, and
`library/skills/index.yaml` from each skill's `skill.yaml`. An index is a
view: it cannot list an asset that does not exist or miss one that does
(PUBLICATION P-07).
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

import yaml  # noqa: E402

from atlas.core import prompts as prompts_mod  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]


def build_skills_index(skills_dir: pathlib.Path) -> dict:
    """One entry per skill directory, read from its `skill.yaml` (L-S1)."""
    skills = []
    for meta_path in sorted(skills_dir.glob("*/skill.yaml")):
        meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
        skills.append(
            {
                "id": meta.get("id", meta_path.parent.name),
                "directory": meta_path.parent.name,
                "name": meta.get("name", meta_path.parent.name),
                "version": str(meta.get("version", "")),
                "capability": meta.get("capability", ""),
                "description": meta.get("description", ""),
            }
        )
    return {"count": len(skills), "skills": skills}


def main() -> int:
    prompts_dir = ROOT / "library" / "prompts"
    index = prompts_mod.build_index(prompts_dir)
    target = prompts_dir / "index.yaml"
    target.write_text(
        "# Generated by scripts/build_library.py. Do not edit by hand.\n"
        + yaml.safe_dump(index, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"wrote {target.relative_to(ROOT)} — {index['count']} prompts, {len(index['categories'])} stages")

    skills_dir = ROOT / "library" / "skills"
    if skills_dir.is_dir():
        skills_index = build_skills_index(skills_dir)
        skills_target = skills_dir / "index.yaml"
        skills_target.write_text(
            "# Generated by scripts/build_library.py. Do not edit by hand.\n"
            + yaml.safe_dump(skills_index, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        print(f"wrote {skills_target.relative_to(ROOT)} — {skills_index['count']} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
